# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.2.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDoubleSpinBox, QFrame,
    QGroupBox, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(760, 520)
        MainWindow.setMinimumSize(QSize(760, 520))
        MainWindow.setMaximumSize(QSize(760, 520))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.backButton = QPushButton(self.centralwidget)
        self.backButton.setObjectName(u"backButton")
        self.backButton.setGeometry(QRect(9, 9, 30, 421))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        self.backButton.setMinimumSize(QSize(30, 0))
        self.backButton.setMaximumSize(QSize(30, 16777215))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(45, 9, 670, 421))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy1)
        self.groupBox.setMinimumSize(QSize(670, 0))
        self.groupBox.setMaximumSize(QSize(650, 800))
        self.groupBox.setCursor(QCursor(Qt.ArrowCursor))
        self.Label_1 = QLabel(self.groupBox)
        self.Label_1.setObjectName(u"Label_1")
        self.Label_1.setGeometry(QRect(10, 10, 131, 28))
        sizePolicy1.setHeightForWidth(self.Label_1.sizePolicy().hasHeightForWidth())
        self.Label_1.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.Label_1.setFont(font)
        self.Label_1.setLayoutDirection(Qt.LeftToRight)
        self.Label_1.setScaledContents(False)
        self.Label_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Label_2 = QLabel(self.groupBox)
        self.Label_2.setObjectName(u"Label_2")
        self.Label_2.setGeometry(QRect(10, 40, 131, 28))
        sizePolicy1.setHeightForWidth(self.Label_2.sizePolicy().hasHeightForWidth())
        self.Label_2.setSizePolicy(sizePolicy1)
        self.Label_2.setFont(font)
        self.Label_2.setLayoutDirection(Qt.LeftToRight)
        self.Label_2.setScaledContents(False)
        self.Label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Label_3 = QLabel(self.groupBox)
        self.Label_3.setObjectName(u"Label_3")
        self.Label_3.setGeometry(QRect(10, 70, 131, 28))
        sizePolicy1.setHeightForWidth(self.Label_3.sizePolicy().hasHeightForWidth())
        self.Label_3.setSizePolicy(sizePolicy1)
        self.Label_3.setFont(font)
        self.Label_3.setLayoutDirection(Qt.LeftToRight)
        self.Label_3.setScaledContents(False)
        self.Label_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Label_4 = QLabel(self.groupBox)
        self.Label_4.setObjectName(u"Label_4")
        self.Label_4.setGeometry(QRect(10, 100, 131, 28))
        sizePolicy1.setHeightForWidth(self.Label_4.sizePolicy().hasHeightForWidth())
        self.Label_4.setSizePolicy(sizePolicy1)
        self.Label_4.setFont(font)
        self.Label_4.setLayoutDirection(Qt.LeftToRight)
        self.Label_4.setScaledContents(False)
        self.Label_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Label_5 = QLabel(self.groupBox)
        self.Label_5.setObjectName(u"Label_5")
        self.Label_5.setGeometry(QRect(10, 130, 131, 28))
        sizePolicy1.setHeightForWidth(self.Label_5.sizePolicy().hasHeightForWidth())
        self.Label_5.setSizePolicy(sizePolicy1)
        self.Label_5.setFont(font)
        self.Label_5.setLayoutDirection(Qt.LeftToRight)
        self.Label_5.setScaledContents(False)
        self.Label_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Label_6 = QLabel(self.groupBox)
        self.Label_6.setObjectName(u"Label_6")
        self.Label_6.setGeometry(QRect(10, 160, 131, 28))
        sizePolicy1.setHeightForWidth(self.Label_6.sizePolicy().hasHeightForWidth())
        self.Label_6.setSizePolicy(sizePolicy1)
        self.Label_6.setFont(font)
        self.Label_6.setLayoutDirection(Qt.LeftToRight)
        self.Label_6.setScaledContents(False)
        self.Label_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Label_7 = QLabel(self.groupBox)
        self.Label_7.setObjectName(u"Label_7")
        self.Label_7.setGeometry(QRect(10, 190, 131, 28))
        sizePolicy1.setHeightForWidth(self.Label_7.sizePolicy().hasHeightForWidth())
        self.Label_7.setSizePolicy(sizePolicy1)
        self.Label_7.setFont(font)
        self.Label_7.setLayoutDirection(Qt.LeftToRight)
        self.Label_7.setScaledContents(False)
        self.Label_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Label_8 = QLabel(self.groupBox)
        self.Label_8.setObjectName(u"Label_8")
        self.Label_8.setGeometry(QRect(10, 220, 131, 28))
        sizePolicy1.setHeightForWidth(self.Label_8.sizePolicy().hasHeightForWidth())
        self.Label_8.setSizePolicy(sizePolicy1)
        self.Label_8.setFont(font)
        self.Label_8.setLayoutDirection(Qt.LeftToRight)
        self.Label_8.setScaledContents(False)
        self.Label_8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SongNameLabel = QLabel(self.groupBox)
        self.SongNameLabel.setObjectName(u"SongNameLabel")
        self.SongNameLabel.setGeometry(QRect(150, 10, 231, 28))
        sizePolicy1.setHeightForWidth(self.SongNameLabel.sizePolicy().hasHeightForWidth())
        self.SongNameLabel.setSizePolicy(sizePolicy1)
        self.SongNameLabel.setFont(font)
        self.SongNameLabel.setLayoutDirection(Qt.LeftToRight)
        self.SongNameLabel.setFrameShape(QFrame.NoFrame)
        self.SongNameLabel.setFrameShadow(QFrame.Plain)
        self.SongNameLabel.setScaledContents(False)
        self.SongNameLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.SongSubNameLabel = QLabel(self.groupBox)
        self.SongSubNameLabel.setObjectName(u"SongSubNameLabel")
        self.SongSubNameLabel.setGeometry(QRect(150, 40, 231, 28))
        sizePolicy1.setHeightForWidth(self.SongSubNameLabel.sizePolicy().hasHeightForWidth())
        self.SongSubNameLabel.setSizePolicy(sizePolicy1)
        self.SongSubNameLabel.setFont(font)
        self.SongSubNameLabel.setLayoutDirection(Qt.LeftToRight)
        self.SongSubNameLabel.setScaledContents(False)
        self.SongSubNameLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.SongArtistLabel = QLabel(self.groupBox)
        self.SongArtistLabel.setObjectName(u"SongArtistLabel")
        self.SongArtistLabel.setGeometry(QRect(150, 70, 231, 28))
        sizePolicy1.setHeightForWidth(self.SongArtistLabel.sizePolicy().hasHeightForWidth())
        self.SongArtistLabel.setSizePolicy(sizePolicy1)
        self.SongArtistLabel.setFont(font)
        self.SongArtistLabel.setLayoutDirection(Qt.LeftToRight)
        self.SongArtistLabel.setScaledContents(False)
        self.SongArtistLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.MapperLabel = QLabel(self.groupBox)
        self.MapperLabel.setObjectName(u"MapperLabel")
        self.MapperLabel.setGeometry(QRect(150, 100, 231, 28))
        sizePolicy1.setHeightForWidth(self.MapperLabel.sizePolicy().hasHeightForWidth())
        self.MapperLabel.setSizePolicy(sizePolicy1)
        self.MapperLabel.setFont(font)
        self.MapperLabel.setLayoutDirection(Qt.LeftToRight)
        self.MapperLabel.setScaledContents(False)
        self.MapperLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.AudioFileLabel = QLabel(self.groupBox)
        self.AudioFileLabel.setObjectName(u"AudioFileLabel")
        self.AudioFileLabel.setGeometry(QRect(150, 160, 231, 28))
        sizePolicy1.setHeightForWidth(self.AudioFileLabel.sizePolicy().hasHeightForWidth())
        self.AudioFileLabel.setSizePolicy(sizePolicy1)
        self.AudioFileLabel.setFont(font)
        self.AudioFileLabel.setLayoutDirection(Qt.LeftToRight)
        self.AudioFileLabel.setScaledContents(False)
        self.AudioFileLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.NJSLabel = QLabel(self.groupBox)
        self.NJSLabel.setObjectName(u"NJSLabel")
        self.NJSLabel.setGeometry(QRect(150, 190, 231, 28))
        sizePolicy1.setHeightForWidth(self.NJSLabel.sizePolicy().hasHeightForWidth())
        self.NJSLabel.setSizePolicy(sizePolicy1)
        self.NJSLabel.setFont(font)
        self.NJSLabel.setLayoutDirection(Qt.LeftToRight)
        self.NJSLabel.setScaledContents(False)
        self.NJSLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.OffsetSpinBox = QDoubleSpinBox(self.groupBox)
        self.OffsetSpinBox.setObjectName(u"OffsetSpinBox")
        self.OffsetSpinBox.setGeometry(QRect(150, 225, 81, 22))
        font1 = QFont()
        font1.setPointSize(12)
        self.OffsetSpinBox.setFont(font1)
        self.OffsetSpinBox.setDecimals(2)
        self.OffsetSpinBox.setMinimum(-4.000000000000000)
        self.OffsetSpinBox.setMaximum(4.000000000000000)
        self.OffsetSpinBox.setSingleStep(0.010000000000000)
        self.comboBox = QComboBox(self.groupBox)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(150, 285, 231, 22))
        self.Label_9 = QLabel(self.groupBox)
        self.Label_9.setObjectName(u"Label_9")
        self.Label_9.setGeometry(QRect(10, 280, 131, 28))
        sizePolicy1.setHeightForWidth(self.Label_9.sizePolicy().hasHeightForWidth())
        self.Label_9.setSizePolicy(sizePolicy1)
        self.Label_9.setFont(font)
        self.Label_9.setLayoutDirection(Qt.LeftToRight)
        self.Label_9.setScaledContents(False)
        self.Label_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.coverLabel = QLabel(self.groupBox)
        self.coverLabel.setObjectName(u"coverLabel")
        self.coverLabel.setGeometry(QRect(405, 22, 240, 240))
        self.addButton = QPushButton(self.groupBox)
        self.addButton.setObjectName(u"addButton")
        self.addButton.setGeometry(QRect(413, 280, 100, 30))
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy2)
        self.addButton.setMinimumSize(QSize(100, 0))
        self.addButton.setMaximumSize(QSize(100, 16777215))
        self.addButton.setFont(font1)
        self.deleteButton = QPushButton(self.groupBox)
        self.deleteButton.setObjectName(u"deleteButton")
        self.deleteButton.setGeometry(QRect(540, 280, 100, 30))
        sizePolicy2.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy2)
        self.deleteButton.setMinimumSize(QSize(100, 0))
        self.deleteButton.setMaximumSize(QSize(100, 16777215))
        self.deleteButton.setFont(font1)
        self.setDefaultOffsetButton = QPushButton(self.groupBox)
        self.setDefaultOffsetButton.setObjectName(u"setDefaultOffsetButton")
        self.setDefaultOffsetButton.setGeometry(QRect(234, 224, 81, 24))
        font2 = QFont()
        font2.setUnderline(True)
        self.setDefaultOffsetButton.setFont(font2)
        self.setDefaultOffsetButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.setDefaultOffsetButton.setFlat(True)
        self.setDefaultNJSButton = QPushButton(self.groupBox)
        self.setDefaultNJSButton.setObjectName(u"setDefaultNJSButton")
        self.setDefaultNJSButton.setGeometry(QRect(234, 194, 81, 24))
        self.setDefaultNJSButton.setFont(font2)
        self.setDefaultNJSButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.setDefaultNJSButton.setFlat(True)
        self.NJSSpinBox = QDoubleSpinBox(self.groupBox)
        self.NJSSpinBox.setObjectName(u"NJSSpinBox")
        self.NJSSpinBox.setGeometry(QRect(150, 195, 81, 22))
        self.NJSSpinBox.setFont(font1)
        self.NJSSpinBox.setDecimals(2)
        self.NJSSpinBox.setMinimum(0.000000000000000)
        self.NJSSpinBox.setMaximum(1000.000000000000000)
        self.NJSSpinBox.setSingleStep(1.000000000000000)
        self.Label_10 = QLabel(self.groupBox)
        self.Label_10.setObjectName(u"Label_10")
        self.Label_10.setGeometry(QRect(10, 250, 131, 28))
        sizePolicy1.setHeightForWidth(self.Label_10.sizePolicy().hasHeightForWidth())
        self.Label_10.setSizePolicy(sizePolicy1)
        self.Label_10.setFont(font)
        self.Label_10.setLayoutDirection(Qt.LeftToRight)
        self.Label_10.setScaledContents(False)
        self.Label_10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.JDLabel = QLabel(self.groupBox)
        self.JDLabel.setObjectName(u"JDLabel")
        self.JDLabel.setGeometry(QRect(150, 250, 231, 28))
        sizePolicy1.setHeightForWidth(self.JDLabel.sizePolicy().hasHeightForWidth())
        self.JDLabel.setSizePolicy(sizePolicy1)
        self.JDLabel.setFont(font)
        self.JDLabel.setLayoutDirection(Qt.LeftToRight)
        self.JDLabel.setScaledContents(False)
        self.JDLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 319, 651, 91))
        self.startLabel = QLabel(self.groupBox_2)
        self.startLabel.setObjectName(u"startLabel")
        self.startLabel.setGeometry(QRect(10, 14, 51, 28))
        sizePolicy1.setHeightForWidth(self.startLabel.sizePolicy().hasHeightForWidth())
        self.startLabel.setSizePolicy(sizePolicy1)
        self.startLabel.setFont(font)
        self.startLabel.setToolTipDuration(-1)
        self.startLabel.setLayoutDirection(Qt.LeftToRight)
        self.startLabel.setScaledContents(False)
        self.startLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.startSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.startSpinBox.setObjectName(u"startSpinBox")
        self.startSpinBox.setGeometry(QRect(70, 19, 71, 22))
        self.startSpinBox.setFont(font1)
        self.startSpinBox.setDecimals(2)
        self.startSpinBox.setMinimum(0.000000000000000)
        self.startSpinBox.setMaximum(100000.000000000000000)
        self.startSpinBox.setSingleStep(1.000000000000000)
        self.endSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.endSpinBox.setObjectName(u"endSpinBox")
        self.endSpinBox.setGeometry(QRect(70, 50, 71, 22))
        self.endSpinBox.setFont(font1)
        self.endSpinBox.setDecimals(2)
        self.endSpinBox.setMinimum(0.000000000000000)
        self.endSpinBox.setMaximum(100000.000000000000000)
        self.endSpinBox.setSingleStep(1.000000000000000)
        self.endLabel = QLabel(self.groupBox_2)
        self.endLabel.setObjectName(u"endLabel")
        self.endLabel.setGeometry(QRect(10, 45, 51, 28))
        sizePolicy1.setHeightForWidth(self.endLabel.sizePolicy().hasHeightForWidth())
        self.endLabel.setSizePolicy(sizePolicy1)
        self.endLabel.setFont(font)
        self.endLabel.setLayoutDirection(Qt.LeftToRight)
        self.endLabel.setScaledContents(False)
        self.endLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.xfadeSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.xfadeSpinBox.setObjectName(u"xfadeSpinBox")
        self.xfadeSpinBox.setGeometry(QRect(520, 19, 71, 22))
        self.xfadeSpinBox.setFont(font1)
        self.xfadeSpinBox.setDecimals(2)
        self.xfadeSpinBox.setMinimum(0.000000000000000)
        self.xfadeSpinBox.setMaximum(100000.000000000000000)
        self.xfadeSpinBox.setSingleStep(1.000000000000000)
        self.xfadeLabel = QLabel(self.groupBox_2)
        self.xfadeLabel.setObjectName(u"xfadeLabel")
        self.xfadeLabel.setGeometry(QRect(450, 14, 61, 28))
        sizePolicy1.setHeightForWidth(self.xfadeLabel.sizePolicy().hasHeightForWidth())
        self.xfadeLabel.setSizePolicy(sizePolicy1)
        self.xfadeLabel.setFont(font)
        self.xfadeLabel.setLayoutDirection(Qt.LeftToRight)
        self.xfadeLabel.setScaledContents(False)
        self.xfadeLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.fadeinLabel = QLabel(self.groupBox_2)
        self.fadeinLabel.setObjectName(u"fadeinLabel")
        self.fadeinLabel.setGeometry(QRect(223, 14, 61, 28))
        sizePolicy1.setHeightForWidth(self.fadeinLabel.sizePolicy().hasHeightForWidth())
        self.fadeinLabel.setSizePolicy(sizePolicy1)
        self.fadeinLabel.setFont(font)
        self.fadeinLabel.setLayoutDirection(Qt.LeftToRight)
        self.fadeinLabel.setScaledContents(False)
        self.fadeinLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.fadeinSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.fadeinSpinBox.setObjectName(u"fadeinSpinBox")
        self.fadeinSpinBox.setGeometry(QRect(293, 19, 71, 22))
        self.fadeinSpinBox.setFont(font1)
        self.fadeinSpinBox.setDecimals(2)
        self.fadeinSpinBox.setMinimum(0.000000000000000)
        self.fadeinSpinBox.setMaximum(100000.000000000000000)
        self.fadeinSpinBox.setSingleStep(1.000000000000000)
        self.fadeoutLabel = QLabel(self.groupBox_2)
        self.fadeoutLabel.setObjectName(u"fadeoutLabel")
        self.fadeoutLabel.setGeometry(QRect(213, 45, 71, 28))
        sizePolicy1.setHeightForWidth(self.fadeoutLabel.sizePolicy().hasHeightForWidth())
        self.fadeoutLabel.setSizePolicy(sizePolicy1)
        self.fadeoutLabel.setFont(font)
        self.fadeoutLabel.setLayoutDirection(Qt.LeftToRight)
        self.fadeoutLabel.setScaledContents(False)
        self.fadeoutLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.fadeoutSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.fadeoutSpinBox.setObjectName(u"fadeoutSpinBox")
        self.fadeoutSpinBox.setGeometry(QRect(293, 50, 71, 22))
        self.fadeoutSpinBox.setFont(font1)
        self.fadeoutSpinBox.setDecimals(2)
        self.fadeoutSpinBox.setMinimum(0.000000000000000)
        self.fadeoutSpinBox.setMaximum(100000.000000000000000)
        self.fadeoutSpinBox.setSingleStep(1.000000000000000)
        self.presilenceLabel = QLabel(self.groupBox_2)
        self.presilenceLabel.setObjectName(u"presilenceLabel")
        self.presilenceLabel.setGeometry(QRect(420, 45, 91, 28))
        sizePolicy1.setHeightForWidth(self.presilenceLabel.sizePolicy().hasHeightForWidth())
        self.presilenceLabel.setSizePolicy(sizePolicy1)
        self.presilenceLabel.setFont(font)
        self.presilenceLabel.setLayoutDirection(Qt.LeftToRight)
        self.presilenceLabel.setScaledContents(False)
        self.presilenceLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.presilenceSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.presilenceSpinBox.setObjectName(u"presilenceSpinBox")
        self.presilenceSpinBox.setGeometry(QRect(520, 50, 71, 22))
        self.presilenceSpinBox.setFont(font1)
        self.presilenceSpinBox.setDecimals(2)
        self.presilenceSpinBox.setMinimum(0.000000000000000)
        self.presilenceSpinBox.setMaximum(100000.000000000000000)
        self.presilenceSpinBox.setSingleStep(1.000000000000000)
        self.Label_18 = QLabel(self.groupBox_2)
        self.Label_18.setObjectName(u"Label_18")
        self.Label_18.setGeometry(QRect(149, 15, 41, 31))
        sizePolicy1.setHeightForWidth(self.Label_18.sizePolicy().hasHeightForWidth())
        self.Label_18.setSizePolicy(sizePolicy1)
        self.Label_18.setFont(font)
        self.Label_18.setLayoutDirection(Qt.LeftToRight)
        self.Label_18.setScaledContents(False)
        self.Label_18.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Label_19 = QLabel(self.groupBox_2)
        self.Label_19.setObjectName(u"Label_19")
        self.Label_19.setGeometry(QRect(149, 46, 41, 31))
        sizePolicy1.setHeightForWidth(self.Label_19.sizePolicy().hasHeightForWidth())
        self.Label_19.setSizePolicy(sizePolicy1)
        self.Label_19.setFont(font)
        self.Label_19.setLayoutDirection(Qt.LeftToRight)
        self.Label_19.setScaledContents(False)
        self.Label_19.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Label_20 = QLabel(self.groupBox_2)
        self.Label_20.setObjectName(u"Label_20")
        self.Label_20.setGeometry(QRect(370, 15, 41, 31))
        sizePolicy1.setHeightForWidth(self.Label_20.sizePolicy().hasHeightForWidth())
        self.Label_20.setSizePolicy(sizePolicy1)
        self.Label_20.setFont(font)
        self.Label_20.setLayoutDirection(Qt.LeftToRight)
        self.Label_20.setScaledContents(False)
        self.Label_20.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.Label_21 = QLabel(self.groupBox_2)
        self.Label_21.setObjectName(u"Label_21")
        self.Label_21.setGeometry(QRect(370, 46, 41, 31))
        sizePolicy1.setHeightForWidth(self.Label_21.sizePolicy().hasHeightForWidth())
        self.Label_21.setSizePolicy(sizePolicy1)
        self.Label_21.setFont(font)
        self.Label_21.setLayoutDirection(Qt.LeftToRight)
        self.Label_21.setScaledContents(False)
        self.Label_21.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.Label_23 = QLabel(self.groupBox_2)
        self.Label_23.setObjectName(u"Label_23")
        self.Label_23.setGeometry(QRect(597, 46, 41, 31))
        sizePolicy1.setHeightForWidth(self.Label_23.sizePolicy().hasHeightForWidth())
        self.Label_23.setSizePolicy(sizePolicy1)
        self.Label_23.setFont(font)
        self.Label_23.setLayoutDirection(Qt.LeftToRight)
        self.Label_23.setScaledContents(False)
        self.Label_23.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.Label_24 = QLabel(self.groupBox_2)
        self.Label_24.setObjectName(u"Label_24")
        self.Label_24.setGeometry(QRect(597, 14, 41, 31))
        sizePolicy1.setHeightForWidth(self.Label_24.sizePolicy().hasHeightForWidth())
        self.Label_24.setSizePolicy(sizePolicy1)
        self.Label_24.setFont(font)
        self.Label_24.setLayoutDirection(Qt.LeftToRight)
        self.Label_24.setScaledContents(False)
        self.Label_24.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.BPMLabel = QLabel(self.groupBox)
        self.BPMLabel.setObjectName(u"BPMLabel")
        self.BPMLabel.setGeometry(QRect(150, 130, 231, 28))
        sizePolicy1.setHeightForWidth(self.BPMLabel.sizePolicy().hasHeightForWidth())
        self.BPMLabel.setSizePolicy(sizePolicy1)
        self.BPMLabel.setFont(font)
        self.BPMLabel.setLayoutDirection(Qt.LeftToRight)
        self.BPMLabel.setScaledContents(False)
        self.BPMLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.outputButton = QPushButton(self.centralwidget)
        self.outputButton.setObjectName(u"outputButton")
        self.outputButton.setGeometry(QRect(590, 450, 100, 30))
        self.outputButton.setMinimumSize(QSize(100, 0))
        self.outputButton.setMaximumSize(QSize(100, 16777215))
        self.outputButton.setFont(font1)
        self.nextButton = QPushButton(self.centralwidget)
        self.nextButton.setObjectName(u"nextButton")
        self.nextButton.setGeometry(QRect(720, 9, 30, 421))
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setMinimumSize(QSize(30, 0))
        self.nextButton.setMaximumSize(QSize(30, 16777215))
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(423, 454, 161, 22))
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy3)
        self.lineEdit.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.imapLabel_2 = QLabel(self.centralwidget)
        self.imapLabel_2.setObjectName(u"imapLabel_2")
        self.imapLabel_2.setEnabled(True)
        self.imapLabel_2.setGeometry(QRect(361, 446, 60, 36))
        sizePolicy4 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(1)
        sizePolicy4.setHeightForWidth(self.imapLabel_2.sizePolicy().hasHeightForWidth())
        self.imapLabel_2.setSizePolicy(sizePolicy4)
        self.imapLabel_2.setMinimumSize(QSize(60, 0))
        self.imapLabel_2.setFont(font1)
        self.iSlotLabel = QLabel(self.centralwidget)
        self.iSlotLabel.setObjectName(u"iSlotLabel")
        self.iSlotLabel.setEnabled(True)
        self.iSlotLabel.setGeometry(QRect(45, 450, 221, 31))
        sizePolicy4.setHeightForWidth(self.iSlotLabel.sizePolicy().hasHeightForWidth())
        self.iSlotLabel.setSizePolicy(sizePolicy4)
        self.iSlotLabel.setMinimumSize(QSize(100, 0))
        font3 = QFont()
        font3.setPointSize(18)
        self.iSlotLabel.setFont(font3)
        self.iSlotLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 760, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"BeatSaberMapMixer", None))
        self.backButton.setText(QCoreApplication.translate("MainWindow", u"\u25c0", None))
        self.groupBox.setTitle("")
        self.Label_1.setText(QCoreApplication.translate("MainWindow", u"Song Name :", None))
        self.Label_2.setText(QCoreApplication.translate("MainWindow", u"Song SubName :", None))
        self.Label_3.setText(QCoreApplication.translate("MainWindow", u"Song Artist :", None))
        self.Label_4.setText(QCoreApplication.translate("MainWindow", u"Mapper :", None))
        self.Label_5.setText(QCoreApplication.translate("MainWindow", u"BPM :", None))
        self.Label_6.setText(QCoreApplication.translate("MainWindow", u"Audio File Name :", None))
        self.Label_7.setText(QCoreApplication.translate("MainWindow", u"Note Jump Speed :", None))
        self.Label_8.setText(QCoreApplication.translate("MainWindow", u"Note Jump Offset :", None))
        self.SongNameLabel.setText("")
        self.SongSubNameLabel.setText("")
        self.SongArtistLabel.setText("")
        self.MapperLabel.setText("")
        self.AudioFileLabel.setText("")
        self.NJSLabel.setText("")
        self.Label_9.setText(QCoreApplication.translate("MainWindow", u"Level :", None))
        self.coverLabel.setText("")
        self.addButton.setText(QCoreApplication.translate("MainWindow", u"\u30de\u30c3\u30d7\u9078\u629e", None))
        self.deleteButton.setText(QCoreApplication.translate("MainWindow", u"\u30de\u30c3\u30d7\u524a\u9664", None))
        self.setDefaultOffsetButton.setText(QCoreApplication.translate("MainWindow", u"\u65e2\u5b9a\u5024\u306b\u623b\u3059", None))
        self.setDefaultNJSButton.setText(QCoreApplication.translate("MainWindow", u"\u65e2\u5b9a\u5024\u306b\u623b\u3059", None))
        self.Label_10.setText(QCoreApplication.translate("MainWindow", u"Jump Distance :", None))
        self.JDLabel.setText("")
        self.groupBox_2.setTitle("")
#if QT_CONFIG(tooltip)
        self.startLabel.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.startLabel.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.startLabel.setText(QCoreApplication.translate("MainWindow", u"*start :", None))
        self.endLabel.setText(QCoreApplication.translate("MainWindow", u"*end :", None))
        self.xfadeLabel.setText(QCoreApplication.translate("MainWindow", u"*xfade :", None))
        self.fadeinLabel.setText(QCoreApplication.translate("MainWindow", u"*fadein :", None))
        self.fadeoutLabel.setText(QCoreApplication.translate("MainWindow", u"*fadeout :", None))
        self.presilenceLabel.setText(QCoreApplication.translate("MainWindow", u"*presilence :", None))
        self.Label_18.setText(QCoreApplication.translate("MainWindow", u"[beat]", None))
        self.Label_19.setText(QCoreApplication.translate("MainWindow", u"[beat]", None))
        self.Label_20.setText(QCoreApplication.translate("MainWindow", u"[beat]", None))
        self.Label_21.setText(QCoreApplication.translate("MainWindow", u"[beat]", None))
        self.Label_23.setText(QCoreApplication.translate("MainWindow", u"[sec]", None))
        self.Label_24.setText(QCoreApplication.translate("MainWindow", u"[sec]", None))
        self.BPMLabel.setText("")
        self.outputButton.setText(QCoreApplication.translate("MainWindow", u"\u51fa\u529b ", None))
        self.nextButton.setText(QCoreApplication.translate("MainWindow", u"\u25b6", None))
        self.imapLabel_2.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u540d:", None))
        self.iSlotLabel.setText("")
    # retranslateUi

